In [3]:
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 15 11:01:32 2022

@author: Simone
"""

import numpy as np 
import pandas as pd 
from random import randrange
import random
import sklearn
df = pd.read_csv("DCIS_INDDEMOG1.csv", sep='|')
df

,ITTER107,Territorio,TIPO_DATO15,Tipo indicatore,TIME,Seleziona periodo,Value,Flag Codes,Flags
0,IT,Italia,BIRTHRATE,tasso di natalità (per mille abitanti),2002,2002,9.4,NaN,NaN
1,IT,Italia,BIRTHRATE,tasso di natalità (per mille abitanti),2003,2003,9.5,NaN,NaN
2,IT,Italia,BIRTHRATE,tasso di natalità (per mille abitanti),2004,2004,9.7,NaN,NaN
3,IT,Italia,BIRTHRATE,tasso di natalità (per mille abitanti),2005,2005,9.5,NaN,NaN
4,IT,Italia,BIRTHRATE,tasso di natalità (per mille abitanti),2006,2006,9.6,NaN,NaN
...,...,...,...,...,...,...,...,...,...
61097,IT111,Sud Sardegna,MEANAGECH,età media della madre al parto,2016,2016,32.6,NaN,NaN
61098,IT111,Sud Sardegna,MEANAGECH,età media della madre al parto,2017,2017,32.6,NaN,NaN
61099,IT111,Sud Sardegna,MEANAGECH,età media della madre al parto,2018,2018,32.6,NaN,NaN
61100,IT111,Sud Sardegna,MEANAGECH,età media della madre al parto,2019,2019,32.8,NaN,NaN
61101,IT111,Sud Sardegna,MEANAGECH,età media della madre al parto,2020,2020,32.9,e,dato stimato

In [5]:
df = df.drop(['ITTER107','TIPO_DATO15','TIME','Flag Codes','Flags'], axis=1)

In [6]:
for col in df:
    print(df[col].unique())

['Italia' 'Nord' 'Nord-ovest' 'Piemonte' 'Torino' 'Vercelli' 'Biella'
 'Verbano-Cusio-Ossola' 'Novara' 'Cuneo' 'Asti' 'Alessandria'
 "Valle d'Aosta / Vallée d'Aoste" 'Liguria' 'Imperia' 'Savona' 'Genova'
 'La Spezia' 'Lombardia' 'Varese' 'Como' 'Lecco' 'Sondrio' 'Milano'
 'Bergamo' 'Brescia' 'Pavia' 'Lodi' 'Cremona' 'Mantova' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Bolzano / Bozen' 'Provincia Autonoma Trento' 'Trento' 'Veneto' 'Verona'
 'Vicenza' 'Belluno' 'Treviso' 'Venezia' 'Padova' 'Rovigo'
 'Friuli-Venezia Giulia' 'Pordenone' 'Udine' 'Gorizia' 'Trieste'
 'Emilia-Romagna' 'Piacenza' 'Parma' "Reggio nell'Emilia" 'Modena'
 'Bologna' 'Ferrara' 'Ravenna' 'Forlì-Cesena' 'Rimini' 'Centro' 'Toscana'
 'Massa-Carrara' 'Lucca' 'Pistoia' 'Firenze' 'Prato' 'Livorno' 'Pisa'
 'Arezzo' 'Siena' 'Grosseto' 'Umbria' 'Perugia' 'Terni' 'Marche'
 'Pesaro e Urbino' 'Ancona' 'Macerata' 'Ascoli Piceno' 'Lazio' 'Viterbo'
 'Rieti' 'Roma' 'Latina' 'Frosinone' 'Mezzogiorno' 'Sud' 'Abruzzo'
 "L'Aquila" 'Teramo' 'Pescara' 'Chieti' 'Molise' 'Isernia' 'Campobasso'
 'Campania' 'Caserta' 'Benevento' 'Napoli' 'Avellino' 'Salerno' 'Puglia'
 'Foggia' 'Bari' 'Taranto' 'Brindisi' 'Lecce' 'Basilicata' 'Potenza'
 'Matera' 'Calabria' 'Cosenza' 'Crotone' 'Catanzaro' 'Vibo Valentia'
 'Reggio di Calabria' 'Isole' 'Sicilia' 'Trapani' 'Palermo' 'Messina'
 'Agrigento' 'Caltanissetta' 'Enna' 'Catania' 'Ragusa' 'Siracusa'
 'Sardegna' 'Sassari' 'Nuoro' 'Cagliari' 'Oristano'
 'Monza e della Brianza' 'Fermo' 'Barletta-Andria-Trani' 'Sud Sardegna']
['tasso di natalità (per mille abitanti)'
 'tasso di mortalità (per mille abitanti)'
 'tasso di nuzialità (per mille abitanti)'
 'saldo migratorio interno (per mille abitanti)'
 "saldo migratorio con l'estero (per mille abitanti)"
 'saldo migratorio per altro motivo (per mille abitanti)'
 'saldo migratorio totale (per mille abitanti)'
 'crescita naturale (per mille abitanti)'
 'tasso di crescita totale (per mille abitanti)'
 'numero medio di figli per donna' 'età media della madre al parto'
 'speranza di vita alla nascita - maschi'
 'speranza di vita a 65 anni - maschi'
 'speranza di vita alla nascita - femmine'
 'speranza di vita a 65 anni - femmine'
 'popolazione 0-14 anni al 1° gennaio (valori percentuali) - al 1° gennaio'
 'popolazione 15-64 anni (valori percentuali) - al 1° gennaio'
 'popolazione 65 anni e più (valori percentuali) - al 1° gennaio'
 'indice di dipendenza strutturale (valori percentuali) - al 1° gennaio'
 'indice di dipendenza degli anziani (valori percentuali) - al 1° gennaio'
 'indice di vecchiaia (valori percentuali) - al 1° gennaio'
 'età media della popolazione - al 1° gennaio'
 'speranza di vita alla nascita - totale'
 'speranza di vita a 65 anni - totale']
[2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 2016 2017 2018 2019 2020 2021]
[  9.4   9.5   9.7 ... 243.3 255.5 265.5]

In [8]:
df1 = df.loc[df['Seleziona periodo'] == 2021]

In [23]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df1['Territorio']. value_counts())

Valle d'Aosta / Vallée d'Aoste        14
Italia                                 7
Isernia                                7
L'Aquila                               7
Teramo                                 7
Pescara                                7
Chieti                                 7
Molise                                 7
Campobasso                             7
Sud                                    7
Campania                               7
Caserta                                7
Benevento                              7
Napoli                                 7
Avellino                               7
Salerno                                7
Abruzzo                                7
Mezzogiorno                            7
Foggia                                 7
Frosinone                              7
Latina                                 7
Roma                                   7
Rieti                                  7
Viterbo                                7
Lazio                                  7
Ascoli Piceno                          7
Macerata                               7
Ancona                                 7
Pesaro e Urbino                        7
Marche                                 7
Terni                                  7
Perugia                                7
Umbria                                 7
Puglia                                 7
Bari                                   7
Siena                                  7
Messina                                7
Barletta-Andria-Trani                  7
Fermo                                  7
Monza e della Brianza                  7
Oristano                               7
Cagliari                               7
Nuoro                                  7
Sassari                                7
Sardegna                               7
Siracusa                               7
Ragusa                                 7
Catania                                7
Enna                                   7
Caltanissetta                          7
Agrigento                              7
Palermo                                7
Taranto                                7
Trapani                                7
Sicilia                                7
Isole                                  7
Reggio di Calabria                     7
Vibo Valentia                          7
Catanzaro                              7
Crotone                                7
Cosenza                                7
Calabria                               7
Matera                                 7
Potenza                                7
Basilicata                             7
Lecce                                  7
Brindisi                               7
Grosseto                               7
Arezzo                                 7
Nord                                   7
Lombardia                              7
Provincia Autonoma Bolzano / Bozen     7
Trentino Alto Adige / Südtirol         7
Nord-est                               7
Mantova                                7
Cremona                                7
Lodi                                   7
Pavia                                  7
Brescia                                7
Bergamo                                7
Milano                                 7
Sondrio                                7
Lecco                                  7
Como                                   7
Varese                                 7
La Spezia                              7
Provincia Autonoma Trento              7
Genova                                 7
Savona                                 7
Imperia                                7
Liguria                                7
Alessandria                            7
Asti                                   7
Cuneo                                  7
Novara                                 7
Verbano-Cusio-Ossola                   7
Biella                                 7
Vercelli                               7
Torino                                 7
Piemonte                               7
Nord-ovest                             7
Bolzano / Bozen                        7
Trento                                 7
Pisa                                   7
Reggio nell'Emilia                     7
Livorno                                7
Prato                                  7
Firenze                                7
Pistoia                                7
Lucca                                  7
Massa-Carrara                          7
Toscana                                7
Centro                                 7
Rimini                                 7
Forlì-Cesena                           7
Ravenna                                7
Ferrara                                7
Bologna                                7
Modena                                 7
Parma                                  7
Veneto                                 7
Piacenza                               7
Emilia-Romagna                         7
Trieste                                7
Gorizia                                7
Udine                                  7
Pordenone                              7
Friuli-Venezia Giulia                  7
Rovigo                                 7
Padova                                 7
Venezia                                7
Treviso                                7
Belluno                                7
Vicenza                                7
Verona                                 7
Sud Sardegna                           7
Name: Territorio, dtype: int64

In [26]:
df1= df1.drop_duplicates()
df1

,Territorio,Tipo indicatore,Seleziona periodo,Value
287,Italia,popolazione 0-14 anni al 1° gennaio (valori pe...,2021,12.8
307,Italia,popolazione 15-64 anni (valori percentuali) - ...,2021,63.8
327,Italia,popolazione 65 anni e più (valori percentuali)...,2021,23.4
347,Italia,indice di dipendenza strutturale (valori perce...,2021,56.8
367,Italia,indice di dipendenza degli anziani (valori per...,2021,36.8
...,...,...,...,...
60850,Sud Sardegna,popolazione 65 anni e più (valori percentuali)...,2021,26.9
60870,Sud Sardegna,indice di dipendenza strutturale (valori perce...,2021,58.6
60890,Sud Sardegna,indice di dipendenza degli anziani (valori per...,2021,42.6
60910,Sud Sardegna,indice di vecchiaia (valori percentuali) - al ...,2021,265.5
60930,Sud Sardegna,età media della popolazione - al 1° gennaio,2021,48.7

In [28]:
df1 = df1.drop(['Seleziona periodo'], axis=1)
df1.to_csv("Indice_demografico.csv", encoding='utf-8',index=False)